/*
 * Copyright 2016 Sai Pullabhotla.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.jmethods.catatumbo;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Specifies the ID of an entity. Identifiers uniquely identify a given entity within the Cloud
 * Datastore. Cloud Datastore supports Integer (64-bit) and String types for identifiers, therefore
 * this annotation is only valid for the following field types:
 * <ul>
 * <li>Primitive long (long)</li>
 * <li>Long Wrapper (java.lang.Long)</li>
 * <li>String (java.lang.String)</li>
 * <li>Any other type that satisfies the following criteria:
 * <ul>
 * <li>Has a public <code>getValue</code> method with no parameters and a return type of long, Long
 * or String</li>
 * <li>Has a public constructor with a single parameter whose type is same as the return type of
 * <code>getValue</code> method.</li>
 * </ul>
 * </li>
 * </ul>
 * 
 * <p>
 * Note that Identifier fields cannot have a custom name in the Cloud Datastore. The Datastore names
 * them wither Id or Name depending on the data type long or String.
 * </p>
 *
 * @author Sai Pullabhotla
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Identifier {

  /**
   * Specifies if identifiers should be generated automatically when inserting new entities into the
   * Cloud Datastore. When <code>autoGenerated</code> is set to <code>true</code> -
   * <ul>
   * <li>If the data type is long or Long - the Identifier generation is delegated to the Cloud
   * Datastore. In other words, the Cloud Datastore allocates the identifiers.</li>
   * <li>If the data type is String - the framework generates the identifier using a random
   * UUID.</li>
   * </ul>
   * When <code>autoGenerated</code> is set to <code>false</code>, the application is responsible
   * for managing the identifiers.
   *
   * @return whether or not to auto generate identifiers
   */
  boolean autoGenerated() default true;
}
